SECRET_KEY: ENC[AES256_GCM,data:u6doFxRRBBU=,iv:oTHu76s9l443FqBEQU1UxpY1T4RoiUAnrS+Gd2sG21A=,tag:nWRiLS1cyZVYneTzdhl+kQ==,type:str]
CLIENT_ID: ENC[AES256_GCM,data:IA+KSvbO9cE=,iv:WcnAaROf+PDi7A13ihSLIrd7oUxK/TCR4Gqa+SIj8EQ=,tag:pJ6MzbUqSaoTPdRpmh2vtw==,type:str]
CLIENT_SECRET: ENC[AES256_GCM,data:cFdjBDvOIk4=,iv:kcgs+mwzRJccW1pql9VlKQ4nPqPwdO8tBoc+Mv2M6Wo=,tag:tSWtF1RwSmxdLecm0dFfIA==,type:str]
sops:
    age:
        - recipient: age1hkeyzs454rgc59xgluayhhqrp3e66zkn02ax7etr9tzlpuh0vqtqnz44h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCa1pFS0RLUC9tTXV2c3RY
            VlJwd3V2dlQxNllJbDBpcEJ3eElLdy9mbndRCjN2eFlyeFFFa3Z5dTIzMVJiV0Ro
            YzEvVTFIRWpLK2UvRW9LSkZkekU3SUEKLS0tIGw1eTJpNFZHVmlvVlp4UnQ3Nkw4
            L1ozeHFWVjFHS0E4aWlVbTFyWjRQYTQKNxGr3dTtvqozv2relz0ttqxu7apT6Rl2
            fRruhGAbWM8JpdwhC6gt4b0k0JLPlKrFtmKe+5fhEgZP2KT8b8wiXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T02:02:05Z"
    mac: ENC[AES256_GCM,data:bOYhpatQI0/funZdLa35k4BOrH6MbWETeXF2vozwgpgcYaPYzdMGYMV2BtQoDW5Gn7tPWvP/+uYd1cXRiQYp9Tm/hznI2cJzW4rnd/U5mTr7BwUc1V0afbSG32KmOWXGp0aREfCs86IqEYBtdHB9+Wm2Uf/ZzFunegIb0h3L7ww=,iv:/iThyCv6IesKuNI8Dw1ThOOuzCe1FzFFlYCXgylRRYc=,tag:2tdqHRp0wWB+13pYxS4AIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
