SECRET_KEY: ENC[AES256_GCM,data:7a38sN4fk17s/QKZ5T7XIUPhbEQv0IuE,iv:qnRDr9rhN0mbxfNO1QMRlo56XiCPXYl4oaOEfXJNJmY=,tag:6aSrKLU6BzxcvhMAea5juQ==,type:str]
CLIENT_ID: ENC[AES256_GCM,data:RfS0zTSiY3T6ikzWobhfznE1SjubGKXvgtrRazlzc9JsR7FlTmHDxZA=,iv:/U1D/tTT+sEN1v9/cUSzuyF8oRU6vrO5WUCKKBMTW/M=,tag:diFqiYa5Q+DxWigMAk28Pw==,type:str]
CLIENT_SECRET: ENC[AES256_GCM,data:OQjfGTY6144QX0c+v3ZUKQRhazcRre6kC9ollpt9vGA=,iv:WzE2Ubtas6aRB7468N50GIToEvRWpr89cSd8UR1u0dE=,tag:yHTT9FMm0788dyt4eG9YgQ==,type:str]
sops:
    age:
        - recipient: age1msgf79zw73wv0ljjqw5evjk8hst6y82e5vu6rws8jcntmfk24ulq69erw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsczJhMnd3U1diUGpiVzFS
            RmRYY0M4QlY2akppb2RXUWZZb09FMWZMTDJBCnExbmVUN0s0L2p3allLNk0rUDdM
            eUZDQXdKUHd6d0wzSnU2OTdXbitKQncKLS0tIFAyWUQrUzRnRXNsVWhQU2NwWlFk
            T1JrUVVCUlVMNjZiM3ZBaG5tNU1hSU0K2vbWc/1yUI+NUI1d4i4vUN/25vwbBKcc
            D8e97cMWjV23t7RGXmsMgDtec1AvtQMN80i7d4K1lBYTSjbhB/gO1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T01:16:08Z"
    mac: ENC[AES256_GCM,data:uHscpKMGMa6hM6sXPzQZds7pa1dZRRrV/ANLeC5ntosoyKvCsIFhgPRg1sGdz26ezOYqCsmkTej3gV8Yni+qOITr+Jlq/+RuJhYBGnIIh1dT8KfsBY2sJCj31uFuqL2cEaUlS7zSwP8cbaUbkqLPpUD4ASVq/Zyi7MaXnVWR2dI=,iv:+5fcnBnXBrINWt1Hpd5SbSUE9SEcW7lLlsI4+NjOhDQ=,tag:JZVOKOEtiuFUHxKVG7AmXw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
