SECRET_KEY: ENC[AES256_GCM,data:kYn6JjDLk/ZC5D7tPmqP/nisCPuJ2xxqplRQ46R/r83UeDtfnaB/9I0mRQ==,iv:JVtmKpBrLbbJPgXcXDHgfe0CLZZ+T3xD7xV6v5OfGh0=,tag:6pE5xnbV32GMegDB0VlfBg==,type:str]
CLIENT_ID: ENC[AES256_GCM,data:RfS0zTSiY3T6ikzWobhfznE1SjubGKXvgtrRazlzc9JsR7FlTmHDxZA=,iv:/U1D/tTT+sEN1v9/cUSzuyF8oRU6vrO5WUCKKBMTW/M=,tag:diFqiYa5Q+DxWigMAk28Pw==,type:str]
CLIENT_SECRET: ENC[AES256_GCM,data:OQjfGTY6144QX0c+v3ZUKQRhazcRre6kC9ollpt9vGA=,iv:WzE2Ubtas6aRB7468N50GIToEvRWpr89cSd8UR1u0dE=,tag:yHTT9FMm0788dyt4eG9YgQ==,type:str]
sops:
    age:
        - recipient: age1msgf79zw73wv0ljjqw5evjk8hst6y82e5vu6rws8jcntmfk24ulq69erw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsczJhMnd3U1diUGpiVzFS
            RmRYY0M4QlY2akppb2RXUWZZb09FMWZMTDJBCnExbmVUN0s0L2p3allLNk0rUDdM
            eUZDQXdKUHd6d0wzSnU2OTdXbitKQncKLS0tIFAyWUQrUzRnRXNsVWhQU2NwWlFk
            T1JrUVVCUlVMNjZiM3ZBaG5tNU1hSU0K2vbWc/1yUI+NUI1d4i4vUN/25vwbBKcc
            D8e97cMWjV23t7RGXmsMgDtec1AvtQMN80i7d4K1lBYTSjbhB/gO1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T12:00:37Z"
    mac: ENC[AES256_GCM,data:Tq2X6gSW56EvbWBxeXX82FCELdHOC37HWdBpujKtZBPioLUhcOiGjSBVoQVS+pxkLLAaZ4TUkZXZZ6r5Rmn6wh0be4ke+hy+hE5NlBU9H9e2jRULiafIGINDn6FF6USYgLuTqCZZ6OoukHpkNb7WsagfaXZZtF/SNn5tsL7ovv8=,iv:iilEzoZnkAzEEvb+SMCQB10W4aafzAm7kkUze1neoeg=,tag:BjersIyT/0OnmY7+o5vvTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
