FOO: ENC[AES256_GCM,data:U0ru,iv:Be7YKPeSN1aUXN5hpM+UseGTm8eFZLQ0e/ZYcZGZorQ=,tag:e0dnwH2we2cumdk+d07Amg==,type:str]
sops:
    age:
        - recipient: age1msgf79zw73wv0ljjqw5evjk8hst6y82e5vu6rws8jcntmfk24ulq69erw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsczJhMnd3U1diUGpiVzFS
            RmRYY0M4QlY2akppb2RXUWZZb09FMWZMTDJBCnExbmVUN0s0L2p3allLNk0rUDdM
            eUZDQXdKUHd6d0wzSnU2OTdXbitKQncKLS0tIFAyWUQrUzRnRXNsVWhQU2NwWlFk
            T1JrUVVCUlVMNjZiM3ZBaG5tNU1hSU0K2vbWc/1yUI+NUI1d4i4vUN/25vwbBKcc
            D8e97cMWjV23t7RGXmsMgDtec1AvtQMN80i7d4K1lBYTSjbhB/gO1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-10T02:10:31Z"
    mac: ENC[AES256_GCM,data:+SfxLGgQUPYZMRF4w9Yg4VWZEsoiC5xsdANcJYK3rFDRlz/v84VKNx+uILHnRgQCQL8TK7rpme2aeLHo1SiRsfVUlAeN0MM7/SqKUy6OpGjmghDk8p5aYEq7LYfHeUIOMpKbaw4ZC71H+aonRUqTb6LeFD8NSO38HNMVaEjICpo=,iv:RuelBnaIEyCfRMQdO8yDv9kaduuZnRrwyWVTsA4fNdY=,tag:gQOyMm4nKk3HCEfgfKVejQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
