SECRET_KEY: ENC[AES256_GCM,data:7a38sN4fk17s/QKZ5T7XIUPhbEQv0IuE,iv:qnRDr9rhN0mbxfNO1QMRlo56XiCPXYl4oaOEfXJNJmY=,tag:6aSrKLU6BzxcvhMAea5juQ==,type:str]
CLIENT_ID: ENC[AES256_GCM,data:RfS0zTSiY3T6ikzWobhfznE1SjubGKXvgtrRazlzc9JsR7FlTmHDxZA=,iv:/U1D/tTT+sEN1v9/cUSzuyF8oRU6vrO5WUCKKBMTW/M=,tag:diFqiYa5Q+DxWigMAk28Pw==,type:str]
CLIENT_SECRET: ENC[AES256_GCM,data:OQjfGTY6144QX0c+v3ZUKQRhazcRre6kC9ollpt9vGA=,iv:WzE2Ubtas6aRB7468N50GIToEvRWpr89cSd8UR1u0dE=,tag:yHTT9FMm0788dyt4eG9YgQ==,type:str]
SENTRY_DSN: ENC[AES256_GCM,data:c2oUsp9kwJ4HRQYjuhDTiF9Owkk9vQWzV89eyD6e3VNL/UYTfKIiuhBx3/0Dul7l8qPwrhL931fngpqg7299WBiuSFC1Gb4UuALaFBRe37dp9dDU7AK1I1wZCzwFGkk=,iv:uI+VPR3LnAGfVT6j6E3UjJKEF5Pnw2fOd/8PpaI56K0=,tag:5Z+FfQF4inNhrp9FajS2og==,type:str]
sops:
    age:
        - recipient: age1msgf79zw73wv0ljjqw5evjk8hst6y82e5vu6rws8jcntmfk24ulq69erw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsczJhMnd3U1diUGpiVzFS
            RmRYY0M4QlY2akppb2RXUWZZb09FMWZMTDJBCnExbmVUN0s0L2p3allLNk0rUDdM
            eUZDQXdKUHd6d0wzSnU2OTdXbitKQncKLS0tIFAyWUQrUzRnRXNsVWhQU2NwWlFk
            T1JrUVVCUlVMNjZiM3ZBaG5tNU1hSU0K2vbWc/1yUI+NUI1d4i4vUN/25vwbBKcc
            D8e97cMWjV23t7RGXmsMgDtec1AvtQMN80i7d4K1lBYTSjbhB/gO1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T01:28:16Z"
    mac: ENC[AES256_GCM,data:otUfFGkFwmOY0zs0VitpD8hQ+BNEfFTWP8h3BmRWM3D0xKFT3dng9HRXYZqB4qn3Y2yZRuT4r56U1oEYFtwgXz/zO/L4uUlcI90ns/dF8iM0UaDtq+LYYjFTApEPz/Z3FHStMRfzo7yGfwiIcRo9YcnN0o1btty4l7kNffZ/jGk=,iv:ZCls1gYq0LeGiCNtCbWD4nAiPMXglOVBSFe7KHd+4hE=,tag:ZGX7VsX7Lxbu25Qik8Mscg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
