version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "daily"
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "daily"
