repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
        stages: [ pre-commit ]
      - id: check-yaml
        stages: [ pre-commit ]
      - id: trailing-whitespace
        stages: [ pre-commit ]
      - id: end-of-file-fixer
        stages: [ pre-commit ]
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [ pre-commit ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        stages: [ pre-commit ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi ]
        stages: [ pre-commit ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        stages: [ manual ]
      - id: ruff-format
        types_or: [ python, pyi ]
        args: [ --check ]
        stages: [ manual ]
