# Container Variables Configuration
# This file specifies environment-specific variables that will be added to or override
# the environment variables extracted from terraform configuration

environments:
  production:

  qa:

  test:

  preview:

  training:

  sandbox-alpha:
    ROOT_URL: https://sandbox-alpha.mavistesting.com/reporting/
    MAVIS_ROOT_URL: https://sandbox-alpha.mavistesting.com/
    
  sandbox-beta: