# Container Variables Configuration
# This file specifies environment-specific variables that will be added to or override
# the environment variables extracted from terraform configuration
# Container Variables Configuration
# This file specifies environment-specific variables that will be added to or override
# the environment variables extracted from terraform configuration

environments:
  production:

  qa:

  test:

  preview:

  training:

  sandbox-alpha:

  sandbox-beta:

# Tunable Variables Configuration
# This section specifies environment-specific variables that will be populated into the SSM parameter store
# at /${environment}/envs/<server_type> and pulled on task startup. These variables can be modified in the cloud
# console or via the AWS CLI and picked up after tasks are restarted, reducing the need to redeploy.
tunable_vars:
  production:

  qa:

  test:

  preview:

  training:

  sandbox-alpha:

  sandbox-beta:
